name: CI

on: [push, pull_request]

jobs:
  retrieve_cache:
    uses: spacetelescope/webbpsf/.github/workflows/retrieve_cache.yml@develop
    with:
      minimal: true
  tests:
    needs: [ retrieve_cache ]
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Coverage test in Python 3
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-poppydev-pysiafdev-cov

          - name: Check for Sphinx doc build errors
            os: ubuntu-latest
            python: '3.10'
            toxenv: docbuild

          - name: Try Astropy development version
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-astropydev-test

          - name: Try latest versions of all dependencies
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-latest-test

          - name: Try minimum supported versions
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-legacy-test

          - name: Try released POPPY and PySIAF
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-stable-test
            continue-on-error: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python dependencies
      run: pip install tox tox-conda>=0.2

    - name: Get WebbPSF Data
      uses: actions/cache/restore@v4
      with:
        path: ${{ runner.temp }}/webbpsf-data
        key: ${{ needs.retrieve_cache.outputs.cache_key }}

    - name: Set WebbPSF data path
      run: echo "WEBBPSF_PATH=${{ needs.retrieve_cache.outputs.cache_path }}" >> $GITHUB_ENV

    - name: Check conda info
      run: conda info

    - name: Run tests with requirements file
      if: ${{ contains(matrix.toxenv,'-latest') }}
      run: |
        cp requirements.txt ${{ runner.temp }}
        tox -e ${{ matrix.toxenv }}

    - name: Run tests
      if: ${{ matrix.continue-on-error == null && contains(matrix.toxenv,'-latest') != true }}
      run: tox -e ${{ matrix.toxenv }}

    - name: Run tests and allow failures
      if: matrix.continue-on-error
      continue-on-error: true
      run: tox -e ${{ matrix.toxenv }}

    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
